package proxy_c

import (
	"bytes"
	byteutil "util/byte"
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"time"
	logging "github.com/op/go-logging"
	uuid "code.google.com/p/go-uuid/uuid"
)

// ==== MAIN - START

func Proxy() {
	logLevel = flag.String("logLevel", "WARN", "Set the log level as \"CRITICAL\", \"ERROR\", \"WARNING\", \"NOTICE\", \"INFO\" or \"DEBUG\"")
	flag.Parse()

	go Server(1024, 1025, 1026)

	time.Sleep(1000 * time.Millisecond)

	proxy, err := NewLoadBalancer(
		&net.TCPAddr{IP: net.IPv4(127, 0, 0, 1), Port: 1234},
		&net.TCPAddr{IP: net.IPv4(127, 0, 0, 1), Port: 1024},
		3,
	)
	if proxy != nil && proxy.listener != nil {
		proxy.Run()
	} else {
		log.Fatalf("Error opening socket - %s", err)
	}
}

// ==== MAIN - END

// ==== READ - START

func read(next func(*chunkContext), src io.Reader, complete func(*chunkContext)) func(*chunkContext) {
	return func(context *chunkContext) {
		defer trace(time.Now(), context.performance.read)
		loggerFactory().Info("Read Stage START - %s", context)
		var loopCounter = 0
		for {
			loggerFactory().Info("Read Loop START - %d - %s", loopCounter, context)
			context.data = context.data[0:cap(context.data)]
			readSize, readError := src.Read(context.data)
			context.data = context.data[0:readSize]

			if readSize > 0 {
				context.totalReadSize += int64(readSize)
				next(context)
				if context.firstChunk {
					context.firstChunk = false
				}
			}

			if readError == io.EOF {
				loggerFactory().Info("Read Loop EOF - %s", context)
				break
			}

			if readError != nil {
				loggerFactory().Info("Read Loop error %s - %s", readError, context)
				context.err = readError
				break
			}

			loggerFactory().Info("Read Loop END - %d - %s", loopCounter, context)
			loopCounter++
		}
		complete(context)
		loggerFactory().Info("Read Stage END - %s", context)
	}
}

// ==== READ - END

// ==== ROUTE - START

var (
	cookieHeaderRegex = regexp.MustCompile("Cookie: .*dynsoftup=([a-z0-9-]*);.*")
)

// test firstChunk and clientToServer
// 	- should
// 		1. read dynsofyup cookie
// 		2. create backpipe
// 		3. call next

// test firstChunk and not clientToServer and no requestUUID
// 	- should
// 		1. add cookie with new UUID value
// 		2. call next

// test firstChunk and not clientToServer and context.requestUUID
// 	- should
// 		1. add cookie with context.requestUUID
// 		2. call next

// test not firstChunk
// 	- should
// 		1. do not create backpipe
// 		2. do not add cookie
// 		3. call next
func route(next func(*chunkContext), uuidGenerator func() uuid.UUID, createBackPipe func(context *chunkContext)) func(*chunkContext) {
	return func(context *chunkContext) {
		defer trace(time.Now(), context.performance.route)
		loggerFactory().Info("Route Stage START - %s", context)
		if context.firstChunk {
			if context.clientToServer {
				submatches := cookieHeaderRegex.FindSubmatch(context.data)
				if len(submatches) >= 2 {
					context.requestUUID = uuid.Parse(string(submatches[1]))
					loggerFactory().Info("Route Stage found UUID %s", context)
				}
				go createBackPipe(NewChunkContext("backpipe", context.to, context.from, context.event, context.requestNumber, context.requestUUID, !context.clientToServer))
			} else {
				uuidCookieValue := context.requestUUID
				if uuidCookieValue == nil {
					uuidCookieValue = uuidGenerator()
				}
				setCookieHeader := []byte(fmt.Sprintf("Set-Cookie: dynsoftup=%s;\n", uuidCookieValue.String()))
				//				println("setCookieHeader length: %d \n the context data")
				searchString := "\n"
				insertLocation := bytes.Index(context.data, []byte(searchString))
				if insertLocation > 0 {
					context.data = byteutil.Insert(context.data, insertLocation+len(searchString), setCookieHeader)
					context.totalReadSize += int64(len(setCookieHeader))
				}
			}
		}

		next(context)
		loggerFactory().Info("Route Stage END - %s", context)
	}
}

// ==== ROUTE - END

// ==== WRITE - START

// test chunk no errors
// 	- should
// 		1. call write with context.data once
// 		2. update context.totalWriteSize

// test zero sized chunk
// 	- should
// 		1. not call write

// test chunk none nil error
// 	- should
// 		1. call write with context.data once
// 		2. update context.totalWriteSize
// 		2. set context.err

// test chunk amount written less than amountToWrite
// 	- should
// 		1. call write with context.data once
// 		2. update context.totalWriteSize
// 		2. set context.err as io.ErrShortWrite
func write(dst io.Writer) func(*chunkContext) {
	return func(context *chunkContext) {
		defer trace(time.Now(), context.performance.write)
		loggerFactory().Info("Write Stage START - %s", context)
		amountToWrite := len(context.data)
		if amountToWrite > 0 {
			writeSize, writeError := dst.Write(context.data)
			if writeSize > 0 {
				context.totalWriteSize += int64(writeSize)
				fmt.Printf("context.totalWriteSize: %d - %s\n\n", context.totalWriteSize, context.String())
			}
			if writeError != nil {
				context.err = writeError
			} else if amountToWrite != writeSize {
				context.err = io.ErrShortWrite
			}
		}
		loggerFactory().Info("Write Stage END - %s", context)
	}
}

// ==== WRITE - END

// ==== COMPLETE - START

// TODO TESTS

// test no error
// 	- should
// 		1. read closed

// test syscall.EPIPE error
// 	- should
// 		1. write closed
// 		2. read closed
func complete(context *chunkContext) {
	defer trace(time.Now(), context.performance.complete)
	loggerFactory().Info("Complete Stage START - %s", context)
	if context.err != nil {
		// If the socket we are writing to is shutdown with
		// SHUT_WR, forward it to the other end of the createForwardPipe:
		if err, ok := context.err.(*net.OpError); ok && err.Err == syscall.EPIPE {
			closeWriteError := context.from.CloseWrite()
			loggerFactory().Info("Complete Stage closed WRITE with error %s - %s", closeWriteError, context)
		}
	}
	closeReadError := context.to.CloseRead()
	loggerFactory().Info("Complete Stage closed READ with error %s - %s", closeReadError, context)

	loggerFactory().Info("Complete Stage END - %s", context)
}

// ==== COMPLETE - END

// ==== CLIENT_LOOP - START

func createPipe(context *chunkContext) {
	loggerFactory().Info("Creating forward " + context.description + " START")
	stages := read(
		route(
			write(context.to),
			func() uuid.UUID {
				return uuid.NewUUID()
			},
			createPipe,
		),
		context.from,
		complete,
	)
	stages(context)
	writePerformanceEntry(context)
	context.event <- context.totalWriteSize
	loggerFactory().Info("Creating forward " + context.description + " END")
}

func clientLoop(backendBaseAddr *net.TCPAddr, loadBalanceCount int) func(*net.TCPConn, chan bool) {
	var requestNumber = 0
	return func(client *net.TCPConn, quit chan bool) {
		loggerFactory().Info("Client loop START")
		requestNumber++
		backendAddr := &net.TCPAddr{IP: backendBaseAddr.IP, Port: backendBaseAddr.Port + (requestNumber % loadBalanceCount)}
		backend, err := net.DialTCP("tcp", nil, backendAddr)
		if err != nil {
			log.Printf("Can't forward traffic to backend tcp/%v: %s\n", backendAddr, err)
			client.Close()
		}

		event := make(chan int64)
		go createPipe(NewChunkContext("forwardpipe", client, backend, event, requestNumber, nil, true))

		var transferred int64 = 0
		for i := 0; i < 2; i++ {
			select {
			case written := <-event:
				transferred += written
			case <-quit:
				// Interrupt the two brokers and "join" them.
				client.Close()
				backend.Close()
				for ; i < 2; i++ {
					transferred += <-event
				}
				return
			}
		}
		client.Close()
		backend.Close()
		loggerFactory().Info("Client loop END")
	}
}

// ==== CLIENT_LOOP - END

// ==== LOAD BALANCER - START

type LoadBalancer struct {
	listener     *net.TCPListener
	frontendAddr *net.TCPAddr
	backendAddr  *net.TCPAddr
	loadBalanceCount int
	stop             chan bool
	uuidGenerator func() string
}

func NewLoadBalancer(frontendAddr, backendAddr *net.TCPAddr, loadBalanceCount int) (*LoadBalancer, error) {
	listener, err := net.ListenTCP("tcp", frontendAddr)
	if err != nil {
		return nil, err
	}
	// If the port in frontendAddr was 0 then ListenTCP will have a picked
	// a port to listen on, hence the call to Addr to get that actual port:
	return &LoadBalancer{
		listener:     listener,
		frontendAddr: listener.Addr().(*net.TCPAddr),
		backendAddr:  backendAddr,
		loadBalanceCount: loadBalanceCount,
		stop: make(chan bool),
		uuidGenerator: func() string {
			return uuid.NewUUID().String()
		},
	}, nil
}

func (proxy *LoadBalancer) Run() {
	loggerFactory().Info("Run START")
	quitRequest := make(chan bool)
	defer close(quitRequest)

	running := true
	go func() {
		<-proxy.stop
		running = false
		proxy.listener.Close()
	}()

	clientLoop := clientLoop(proxy.backendAddr, proxy.loadBalanceCount)
	for running {
		client, err := proxy.listener.Accept()
		if err != nil {
			if !isClosedError(err) {
				log.Printf("Stopping proxy on tcp/%v for tcp/%v (%v)", proxy.frontendAddr, proxy.backendAddr, err)
			}
			return
		}
		go clientLoop(client.(*net.TCPConn), quitRequest)
	}
	loggerFactory().Info("Run END")
}

func isClosedError(err error) bool {
	/* This comparison is ugly, but unfortunately, net.go doesn't export errClosing.
	 * See:
	 * http://golang.org/src/pkg/net/net.go
	 * https://code.google.com/p/go/issues/detail?id=4337
	 * https://groups.google.com/forum/#!msg/golang-nuts/0_aaCvBmOcM/SptmDyX1XJMJ
	 */
	return strings.HasSuffix(err.Error(), "use of closed network connection")
}

func (proxy *LoadBalancer) Stop() {
	close(proxy.stop)
}

// ==== LOAD BALANCER - END

// ==== CHUNK_CONTEXT - START

type chunkContext struct {
	description           string
	data                  []byte
	to                    *net.TCPConn
	from                  *net.TCPConn
	err                   error
	totalReadSize         int64
	totalWriteSize        int64
	event                 chan int64
	firstChunk            bool
	performance           performance
	requestNumber         int
	requestUUID           uuid.UUID
	clientToServer        bool
}

type ChunkContext interface {
	String()
}

func (context *chunkContext) String() string {
	var output string = ""
	output += "\n{\n"
	output += fmt.Sprintf("\t description: %s\n", context.description)
	if (context.clientToServer) {
		output += "\t direction: client->server\n"
	} else {
		output += "\t direction: server->client\n"
	}
	if len(context.data) > 0 {
		output += "\t data:\n\t\t"+strings.Replace(string(context.data), "\n", "\n\t\t", -1)
	}
	output += "\n"
	if context.from.LocalAddr() != nil && context.from.RemoteAddr() != nil {
		output += fmt.Sprintf("\t from: %s -> %s\n", context.from.LocalAddr(), context.from.RemoteAddr())
	}
	if context.to.LocalAddr() != nil && context.to.RemoteAddr() != nil {
		output += fmt.Sprintf("\t to: %s -> %s\n", context.to.LocalAddr(), context.to.RemoteAddr())
	}
	output += fmt.Sprintf("\t totalReadSize: %d\n", context.totalReadSize)
	output += fmt.Sprintf("\t totalWriteSize: %d\n", context.totalWriteSize)
	if context.requestUUID != nil {
		output += fmt.Sprintf("\t requestUUID: %s\n", context.requestUUID)
	}
	output += "}\n"
	return output
}

func NewChunkContext(description string, from *net.TCPConn, to *net.TCPConn, event chan int64, requestNumber int, requestUUID uuid.UUID, clientToServer bool) *chunkContext {
	return &chunkContext{
		description: description,
		data: make([]byte, 64*1024),
		from: from,
		to: to,
		event: event,
		firstChunk: true,
		performance: *&performance{
			read: new(int64),
			route: new(int64),
			write: new(int64),
			complete: new(int64),
		},
		requestNumber: requestNumber,
		requestUUID: requestUUID,
		clientToServer: clientToServer,
	}
}

// ==== CHUNK_CONTEXT - END

// ==== PERFORMANCE - START

type performance struct {
	read               *int64
	route              *int64
	write              *int64
	complete           *int64
}

func trace(startTime time.Time, result *int64) {
	*result = int64(time.Since(startTime))
}

var performanceLog = func() *csv.Writer {
	file, error := os.Create("performance_log.csv")

	if error != nil {panic(error)}

	// New Csv writer
	writer := csv.NewWriter(file)

	// Headers
	var new_headers = []string{"count", "read", "route", "write", "complete"}
	returnError := writer.Write(new_headers)
	if returnError != nil {
		loggerFactory().Error("Error writing headers into performance log - %s", returnError)
	}
	writer.Flush()

	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGINT)
	signal.Notify(c, syscall.SIGKILL)
	signal.Notify(c, syscall.SIGTERM)
	signal.Notify(c, syscall.SIGHUP)
	signal.Notify(c, syscall.SIGQUIT)
	go func() {
		<-c
		file.Close()
		os.Exit(1)
	}()

	return writer
}()

func writePerformanceEntry(context *chunkContext) {
	performanceLog.Write([]string{
	strconv.Itoa(context.requestNumber),
	strconv.FormatInt(*context.performance.read, 10),
	strconv.FormatInt(*context.performance.route, 10),
	strconv.FormatInt(*context.performance.write, 10),
	strconv.FormatInt(*context.performance.complete, 10)})
	performanceLog.Flush()
}

// ==== PERFORMANCE - END

// ==== LOGGER - START

var logLevel *string

var loggerFactory = func() func() *logging.Logger {
	var logg *logging.Logger = nil

	return func() *logging.Logger {
		if logg == nil {
			logg = logging.MustGetLogger("main")

			// Customize the output format
			logging.SetFormatter(logging.MustStringFormatter("%{level:8s} - %{message}"))

			// Setup one stdout and one syslog backend
			logBackend := logging.NewLogBackend(os.Stderr, "", log.Ldate|log.Lmicroseconds|log.Lshortfile)
			logBackend.Color = true

			// Combine them both into one logging backend
			logging.SetBackend(logBackend)

			// set log level
			level, _ := logging.LogLevel("WARN")
			if logLevel != nil {
				level, _ = logging.LogLevel(*logLevel)
			}
			logging.SetLevel(level, "main")
		}
		return logg
	}
}()

// ==== LOGGER - END

// ==== SERVER - START

func Server(ports ...int) {
	for _, port := range ports {
		loggerFactory().Info("Starting server %d ...", port)
		go http.ListenAndServe(":"+strconv.Itoa(port), &handle{port})
	}
}

type handle struct {
	Port int
}

func (h *handle) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	time.Sleep(100 * time.Millisecond)
	fmt.Fprintf(w, "ONE, ")
	time.Sleep(10 * time.Millisecond)
	fmt.Fprintf(w, "TWO, ")
	time.Sleep(10 * time.Millisecond)
	fmt.Fprintf(w, "THREE, ")
	time.Sleep(10 * time.Millisecond)
	fmt.Fprintf(w, "FOUR, ")
	time.Sleep(100 * time.Millisecond)
	fmt.Fprintf(w, "FIVE from %d\n", h.Port)
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	w.(http.Flusher).Flush()
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
	//	fmt.Fprintf(w, "A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE_A_VERY_LONG_RESPOSE\n")
}

// ==== SERVER - END




